<a href="https://colab.research.google.com/github/deepakmaurya9648/python-play/blob/main/vector_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

v1 = np.array([1,-1,2])
v2 = np.array([2,5,2])


[3 4 4]


In [2]:
#addition
print(v1+v2)

[3 4 4]


In [3]:
#substraction
print(v1-v2)

[-1 -6  0]


In [4]:
#scaler
print(2*v1)

[ 2 -2  4]


In [5]:
# lenght
print(np.linalg.norm(v1))

2.449489742783178


In [6]:
#dot product
dot = np.dot(v1,v2)
print(dot)

1
